### ISSUE TITLE
Make S3 bucket names configurable.

### ISSUE THREAD

**Issue by bradtreloar** [bradtreloar/site-manager#4]
The S3 bucket name for each site is currently hardcoded as `sitebackup-` followed by the site's hostname.

Add the ability to override this with a custom bucket name in the `sites` config:

Example:

```
sites:
  example.com:
    app: wordpress
    ssh:
      user: exampleuser
    backup:
      bucket: examplebucketname
```
