### ISSUE TITLE
Add ability to create backups for apps other than Wordpress and Drupal

### ISSUE THREAD

**Issue by bradtreloar** [bradtreloar/site-manager#5]
This utility currently handles backups for Wordpress and Drupal, but the backup logic is basically just this:

1. Get the MySQL database credentials
2. Export the database
3. Download files located at certain set of paths.
4. Create a tarball
5. Upload the tarball to AWS S3.

It would help if the underlying backup logic could handle different file structures such as a Laravel app, and be more flexible in discovering database configuration details.

An example of how config could be provided for a Laravel app installed at `/laravel`:

```yaml
sites:
  example.com:
    app:
      paths:
        - /laravel/storage/app
      database:
        environment:
          path: /laravel/.env
          variables:
            database: DB_DATABASE
            username: DB_USERNAME
            password: DB_PASSWORD
            host: DB_HOST
            port: DB_PORT
    ssh:
      user: exampleuser
```

Omitting the `app.paths` key would tell the site manager not to try to download any site files.
Omitting the `app.database` key would tell the site manager not to try to export a database.
The `app.paths` value should be able to exclude paths, as well, by prepending the path with a tilde (`~`).
